name: CI

on: [push]

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  setup-pyenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup venv
        run: |
          python -m venv venv
          source venv/bin/activate
      - uses: actions/cache@v3
        id: pip-cache
        with:
          path: 'venv'
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
      - name: Install packages
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements.txt

  contract-test:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: format check
        run: yarn prettier:check
      - name: contracts test
        run: yarn test

  slither-scan:
    runs-on: ubuntu-latest
    needs: [setup-node, setup-pyenv]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        id: pip-cache
        with:
          path: 'venv'
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
      - name: activate pyenv
        run: source venv/bin/activate
      - name: Slither scan
        run: yarn psummary
